idf_component_register(
    SRCS
        "main.c"
        "kennedy9800.c"
        "psram.c"
        "ltfs.c"
        "fat32_meta.c"
        "disk_io.c"
        "usb_msc.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver
        esp_timer
        esp_psram
        freertos
        tinyusb
        cmsis_freertos
        log
        heap
)
